core/urls.py
from django.urls import path
from . import views

urlpatterns = [
	path('', views.HomeView.as_view(), name="home_page"),
	path('categories/<slug>/', views.CategoryListView.as_view(), name="by_category"),
	path('products/<slug>/', views.ProductDetailView.as_view(), name="product_detail"),
	path('add_to_cart/<slug>/', views.AddToCartView.as_view(), name="add_to_cart"),
	path('remove_from_cart/<slug>/', views.RemoveFromCartView.as_view(), name="remove_from_cart"),
	path('remove_single_item_from_cart/<slug>/', views.RemoveSingleItemFromCartView.as_view(), name="remove_single_item_from_cart"),
	path('checkout/', views.checkout, name="checkout"),
	path('order-summary/', views.OrderSummaryView.as_view(), name="order_summary"),
	path('search', views.SearchView.as_view(), name="search"),
]

core/models.py
from django.conf import settings
from django.db import models
from slugify import slugify
from django.urls import reverse
import uuid
from datetime import datetime
from django_countries.fields import CountryField


LABEL = (
	("N", "New"),
	("T", "Top"),
)

ADDRESS_TYPES = (
	("S", "Shipping"),
	("B", "Billing"),
)

class Item(models.Model):
	id = models.UUIDField(primary_key=True, default=uuid.uuid4, editable=False)
	title = models.CharField(max_length=100)
	brand = models.CharField(max_length=20, blank=True, null=True)
	description = models.TextField(max_length=300)
	label = models.CharField(max_length=1, choices=LABEL, blank=True, null=True)
	image = models.ImageField(upload_to="product_images")
	slug = models.SlugField(max_length=70,  blank=True, null=True, unique=True)
	date_added = models.DateTimeField(auto_now_add=True)
	date_modified = models.DateTimeField(auto_now=True)
	category = models.ForeignKey('Category', on_delete=models.SET_NULL, blank=True, null=True)
	price = models.DecimalField(max_digits=6, decimal_places=2)
	discount_price = models.DecimalField(max_digits=5, decimal_places=2, blank=True, null=True)

	def __str__(self):
		return self.title

	def save(self, *args, **kwargs):
		now = datetime.now()
		if not self.slug:
			self.slug = slugify(self.title + "-" + now.strftime("%f"))

		return super().save(*args, **kwargs)

	def get_absolute_url(self):
		return reverse("product_detail", args=(self.slug,))


	def get_item_price(self):
		if self.discount_price:
			return self.price - self.discount_price
		return self.price


	class Meta:
		ordering = ('-date_added',)


class Category(models.Model):
	name = models.CharField(max_length=30)
	slug = models.SlugField(unique=True, blank=True, null=True)

	def __str__(self):
		return self.name

	def save(self, *args, **kwargs):
		if not self.slug:
			self.slug = slugify(self.name)

		return super().save(*args, **kwargs)


class OrderItem(models.Model):
	user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE, related_name="items")
	item = models.OneToOneField(Item, on_delete=models.CASCADE)
	quantity = models.PositiveIntegerField(default=1)
	ordered = models.BooleanField(default=False)

	def __str__(self):
		return self.item.title


	def get_total_item_price(self):
		return self.item.get_item_price() * self.quantity

	def get_total_discount_price(self):
		if self.item.discount_price:
			return self.item.discount_price * self.quantity
		return 0



class Order(models.Model):
	user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE, related_name="orders")
	items = models.ManyToManyField(OrderItem)
	date_started = models.DateTimeField(auto_now_add=True)
	date_ordered = models.DateTimeField(blank=True, null=True)
	ordered = models.BooleanField(default=False)
	shipping_address = models.OneToOneField("Address", on_delete=models.CASCADE, blank=True, null=True, related_name="shipping_address")
	billing_address = models.OneToOneField("Address", on_delete=models.CASCADE, blank=True, null=True, related_name="billing_address")
	being_delivered = models.BooleanField(default=False)
	received = models.BooleanField(default=False)
	refund_requested = models.BooleanField(default=False)
	refund_granted = models.BooleanField(default=False)
	
	def get_total(self):
		total = 0
		for item in self.items.all():
			total += item.get_total_item_price()

		return total


class Address(models.Model):
	user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
	street_address = models.CharField(max_length=100)
	apartment_address = models.CharField(max_length=100)
	country = CountryField(multiple=False)
	zip_code = models.CharField(max_length=32)
	address_type = models.CharField(max_length=1, choices=ADDRESS_TYPES)
	default = models.BooleanField(default=False)

	def __str__(self):
		return self.street_address

templates/_base.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
	<meta charset="UTF-8">
	<meta name="viewport" content="width=device-width, initial-scale=1.0">
	<title>{% block title %}Welcome to Ecommerce{% endblock title %}</title>
	<!-- Font Awesome -->
  <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.11.2/css/all.css">
  <!-- Bootstrap core CSS -->
  <link href="{% static 'css/bootstrap.min.css' %}" rel="stylesheet">
  <!-- Material Design Bootstrap -->
  <link href="{% static 'css/mdb.min.css' %}" rel="stylesheet">
  <!-- Your custom styles (optional) -->
  <link href="{% static 'css/style.min.css' %}" rel="stylesheet">
</head>
<body>


	{% include '_navbar.html' %}
	
  {% if messages %}
  <ul class="messages" style="width: 100%; max-width: 960px; margin: 0 auto;">
      {% for message in messages %}
        <div class="alert alert-{{ message.tags }} alert-dismissible fade show" role="alert">
        {{ message }}
        <button type="button" class="close" data-dismiss="alert" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      {% endfor %}
  </ul>
  {% endif %}
  
	{% block content %}
	    
	{% endblock content %}

	{% include '_footer.html' %}



	<!-- SCRIPTS -->
  <!-- JQuery -->
  <script type="text/javascript" src="{% static 'js/jquery-3.4.1.min.js' %}"></script>
  <!-- Bootstrap tooltips -->
  <script type="text/javascript" src="{% static 'js/popper.min.js' %}"></script>
  <!-- Bootstrap core JavaScript -->
  <script type="text/javascript" src="{% static 'js/bootstrap.min.js' %}"></script>
  <!-- MDB core JavaScript -->
  <script type="text/javascript" src="{% static 'js/mdb.min.js' %}"></script>
  <!-- Initializations -->
  <script type="text/javascript">
    // Animations initialization
    new WOW().init();

  </script>
</body>
</html>

templates/_footer.html
{% load static %}

  <!--Footer-->
  <footer class="page-footer text-center font-small mt-4 wow fadeIn">
    
    <hr class="my-4">

    <!-- Social icons -->
    <div class="pb-4">
      <a href="https://www.facebook.com/mdbootstrap" target="_blank">
        <i class="fab fa-facebook-f mr-3"></i>
      </a>

      <a href="https://twitter.com/MDBootstrap" target="_blank">
        <i class="fab fa-twitter mr-3"></i>
      </a>

      <a href="https://www.youtube.com/watch?v=7MUISDJ5ZZ4" target="_blank">
        <i class="fab fa-youtube mr-3"></i>
      </a>

      <a href="https://plus.google.com/u/0/b/107863090883699620484" target="_blank">
        <i class="fab fa-google-plus-g mr-3"></i>
      </a>

      <a href="https://dribbble.com/mdbootstrap" target="_blank">
        <i class="fab fa-dribbble mr-3"></i>
      </a>

      <a href="https://pinterest.com/mdbootstrap" target="_blank">
        <i class="fab fa-pinterest mr-3"></i>
      </a>

      <a href="https://github.com/mdbootstrap/bootstrap-material-design" target="_blank">
        <i class="fab fa-github mr-3"></i>
      </a>

      <a href="http://codepen.io/mdbootstrap/" target="_blank">
        <i class="fab fa-codepen mr-3"></i>
      </a>
    </div>
    <!-- Social icons -->

    <!--Copyright-->
    <div class="footer-copyright py-3">
      © 2019 Copyright:
      <a href="https://mdbootstrap.com/education/bootstrap/" target="_blank"> MDBootstrap.com </a>
    </div>
    <!--/.Copyright-->

  </footer>
  <!--/.Footer-->

templates/_navbar.html
{% load static %}
{% load cart_template_tags %}


  <!-- Navbar -->
  <nav class="navbar fixed-top navbar-expand-lg navbar-light white scrolling-navbar">
    <div class="container">

      <!-- Brand -->
      <a href="/" class="navbar-brand waves-effect" href="https://mdbootstrap.com/docs/jquery/">
        <strong class="blue-text">Shohparfum</strong>
      </a>

      <!-- Collapse -->
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent"
        aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>

      <!-- Links -->
      <div class="collapse navbar-collapse" id="navbarSupportedContent">

        <!-- Left -->
        <ul class="navbar-nav mr-auto">
          <li class="nav-item active">
            <a class="nav-link waves-effect" href="#">Home
              <span class="sr-only">(current)</span>
            </a>
          </li>
          <li class="nav-item">
            <a class="nav-link waves-effect" href="https://mdbootstrap.com/docs/jquery/" target="_blank">About</a>
          </li>
        </ul>

        <!-- Right -->
        <ul class="navbar-nav nav-flex-icons">
          {% if user.is_authenticated %}
              <li class="nav-item">
                <a href="{% url 'order_summary' %}" class="nav-link waves-effect">
                  <span class="badge red z-depth-1 mr-1">{{ user|cart_item_count }}</span>
                  <i class="fas fa-shopping-cart"></i>
                  <span class="clearfix d-none d-sm-inline-block">Cart</span>
                </a>
              </li>
              <li class="nav-item">
                <a href="{% url 'account_logout' %}" class="nav-link">Logout</a>
              </li>

          {% else %}
              <li class="nav-item mr-4">
                <a href="{% url 'account_login' %}" class="nav-link">Login</a>
              </li>
              <li class="nav-item">
                <a href="{% url 'account_signup' %}" class="nav-link">Sign up</a>
              </li>
          {% endif %}
        </ul>

      </div>

    </div>
  </nav>
  <div style="width: 100%; height: 80px;">a</div>
  <!-- Navbar -->

templates/_pagination.html
{% if is_paginated %}
    <!--Pagination-->
<nav class="d-flex justify-content-center wow fadeIn">
  <ul class="pagination pg-blue">

    <!--Arrow left-->

    {% if page_obj.has_previous %}
    <li class="page-item ">
      <a class="page-link" href="?page={{ page_obj.previous_page_number }}" aria-label="Previous">
        <span aria-hidden="true">&laquo;</span>
        <span class="sr-only">Previous</span>
      </a>
    </li>
    {% else %}
        <li class="page-item disabled">
          <a class="page-link" href="#" aria-label="Previous">
            <span aria-hidden="true">&laquo;</span>
            <span class="sr-only">Previous</span>
          </a>
        </li>
    {% endif %}

    {% for i in paginator.page_range %}
      {% if page_obj.number == i %}
        <li class="page-item active">
          <a class="page-link" href="#">{{ i }}
            <span class="sr-only">(current)</span>
          
          </a>
        </li>
      {% else %}
          <li class="page-item">
            <a class="page-link" href="?page={{ i }}">{{ i }}</a>
          </li>
      {% endif %}
    {% endfor %}

    {% if page_obj.has_next %}
    <li class="page-item ">
      <a class="page-link" href="?page={{ page_obj.next_page_number }}" aria-label="Previous">
        <span aria-hidden="true">&raquo;</span>
        <span class="sr-only">Next</span>
      </a>
    </li>
    {% else %}
        <li class="page-item disabled">
          <a class="page-link" href="#" aria-label="Previous">
            <span aria-hidden="true">&raquo;</span>
            <span class="sr-only">Next</span>
          </a>
        </li>
    {% endif %}
  </ul>
</nav>
<!--Pagination-->

{% endif %}

templates/home-page.html
{% extends "_base.html" %}

{% load static %}

{% block content %}

  <style type="text/css">
    html,
    body,
    header,
    .carousel {
      height: 60vh;
    }

    @media (max-width: 740px) {

      html,
      body,
      header,
      .carousel {
        height: 100vh;
      }
    }

    @media (min-width: 800px) and (max-width: 850px) {

      html,
      body,
      header,
      .carousel {
        height: 100vh;
      }
    }
  </style>



  <!--Carousel Wrapper-->
  <div id="carousel-example-1z" class="carousel slide carousel-fade pt-4" data-ride="carousel">

    <!--Indicators-->
    <ol class="carousel-indicators">
      <li data-target="#carousel-example-1z" data-slide-to="0" class="active"></li>
      <li data-target="#carousel-example-1z" data-slide-to="1"></li>
      <li data-target="#carousel-example-1z" data-slide-to="2"></li>
    </ol>
    <!--/.Indicators-->

    <!--Slides-->
    <div class="carousel-inner" role="listbox">

      <!--First slide-->
      <div class="carousel-item active">
        <div class="view" style="background-image: url('https://mdbootstrap.com/img/Photos/Horizontal/E-commerce/8-col/img%282%29.jpg'); background-repeat: no-repeat; background-size: cover;">

          <!-- Mask & flexbox options-->
          <div class="mask rgba-black-strong d-flex justify-content-center align-items-center">

            <!-- Content -->
            <div class="text-center white-text mx-5 wow fadeIn">
              <h1 class="mb-4">
                <strong>Learn Bootstrap 4 with MDB</strong>
              </h1>

              <p>
                <strong>Best & free guide of responsive web design</strong>
              </p>

              <p class="mb-4 d-none d-md-block">
                <strong>The most comprehensive tutorial for the Bootstrap 4. Loved by over 500 000 users. Video and
                  written versions
                  available. Create your own, stunning website.</strong>
              </p>

              <a target="_blank" href="https://mdbootstrap.com/education/bootstrap/" class="btn btn-outline-white btn-lg">Start
                free tutorial
                <i class="fas fa-graduation-cap ml-2"></i>
              </a>
            </div>
            <!-- Content -->

          </div>

        </div>
      </div>
      <!--/First slide-->

      <!--Second slide-->
      <div class="carousel-item">
        <div class="view" style="background-image: url('https://mdbootstrap.com/img/Photos/Horizontal/E-commerce/8-col/img%283%29.jpg'); background-repeat: no-repeat; background-size: cover;">

          <!-- Mask & flexbox options-->
          <div class="mask rgba-black-strong d-flex justify-content-center align-items-center">

            <!-- Content -->
            <div class="text-center white-text mx-5 wow fadeIn">
              <h1 class="mb-4">
                <strong>Learn Bootstrap 4 with MDB</strong>
              </h1>

              <p>
                <strong>Best & free guide of responsive web design</strong>
              </p>

              <p class="mb-4 d-none d-md-block">
                <strong>The most comprehensive tutorial for the Bootstrap 4. Loved by over 500 000 users. Video and
                  written versions
                  available. Create your own, stunning website.</strong>
              </p>

              <a target="_blank" href="https://mdbootstrap.com/education/bootstrap/" class="btn btn-outline-white btn-lg">Start
                free tutorial
                <i class="fas fa-graduation-cap ml-2"></i>
              </a>
            </div>
            <!-- Content -->

          </div>
          <!-- Mask & flexbox options-->

        </div>
      </div>
      <!--/Second slide-->

      <!--Third slide-->
      <div class="carousel-item">
        <div class="view" style="background-image: url('https://mdbootstrap.com/img/Photos/Horizontal/E-commerce/8-col/img%285%29.jpg'); background-repeat: no-repeat; background-size: cover;">

          <!-- Mask & flexbox options-->
          <div class="mask rgba-black-strong d-flex justify-content-center align-items-center">

            <!-- Content -->
            <div class="text-center white-text mx-5 wow fadeIn">
              <h1 class="mb-4">
                <strong>Learn Bootstrap 4 with MDB</strong>
              </h1>

              <p>
                <strong>Best & free guide of responsive web design</strong>
              </p>

              <p class="mb-4 d-none d-md-block">
                <strong>The most comprehensive tutorial for the Bootstrap 4. Loved by over 500 000 users. Video and
                  written versions
                  available. Create your own, stunning website.</strong>
              </p>

              <a target="_blank" href="https://mdbootstrap.com/education/bootstrap/" class="btn btn-outline-white btn-lg">Start
                free tutorial
                <i class="fas fa-graduation-cap ml-2"></i>
              </a>
            </div>
            <!-- Content -->

          </div>
          <!-- Mask & flexbox options-->

        </div>
      </div>
      <!--/Third slide-->

    </div>
    <!--/.Slides-->

    <!--Controls-->
    <a class="carousel-control-prev" href="#carousel-example-1z" role="button" data-slide="prev">
      <span class="carousel-control-prev-icon" aria-hidden="true"></span>
      <span class="sr-only">Previous</span>
    </a>
    <a class="carousel-control-next" href="#carousel-example-1z" role="button" data-slide="next">
      <span class="carousel-control-next-icon" aria-hidden="true"></span>
      <span class="sr-only">Next</span>
    </a>
    <!--/.Controls-->

  </div>
  <!--/.Carousel Wrapper-->

  <!--Main layout-->
  <main>
    <div class="container">

      <!--Navbar-->
      <nav class="navbar navbar-expand-lg navbar-dark mdb-color lighten-3 mt-3 mb-5">

        <!-- Navbar brand -->
        <span class="navbar-brand">Categories:</span>

        <!-- Collapse button -->
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#basicExampleNav"
          aria-controls="basicExampleNav" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>

        <!-- Collapsible content -->
        <div class="collapse navbar-collapse" id="basicExampleNav">

          <!-- Links -->
          <ul class="navbar-nav mr-auto">
            <li class="nav-item {% if not active_link %}active{% endif %}">
              <a class="nav-link" href="/">All
                <span class="sr-only">(current)</span>
              </a>
            </li>

            {% for cat in categories %}
            <li class="nav-item {% if cat.id == active_link %}active{% endif %}">
              <a class="nav-link" href="{% url 'by_category' slug=cat.slug %}">{{ cat.name }}</a>
            </li>
            {% endfor %}

          </ul>
          <!-- Links -->

          <form class="form-inline" method="get" action="{% url 'search' %}">
            <div class="md-form my-0">
              <input class="form-control mr-sm-2" name="q" type="text" placeholder="Search" aria-label="Search" required>
            </div>
          </form>
        </div>
        <!-- Collapsible content -->

      </nav>
      <!--/.Navbar-->

      <!--Section: Products v.3-->
      <section class="text-center mb-4">

        <!--Grid row-->
        <div class="row wow fadeIn">


          {% for item in item_list %}
            
          <!--Grid column-->
          <div class="col-lg-3 col-md-6 mb-4">

            <!--Card-->
            <div class="card">

              <!--Card image-->
              <div class="view overlay" style="height: 200px;">
                <img src="{{ item.image.url }}" class="card-img-top" style="width: 100%; height: 100%; object-fit: cover;"
                  alt="">
                <a href="{{ item.get_absolute_url }}">
                  <div class="mask rgba-white-slight"></div>
                </a>
              </div>
              <!--Card image-->

              <!--Card content-->
              <div class="card-body text-center">
                <!--Category & Title-->
                <a href="{% url 'by_category' item.category.slug %}" class="grey-text">
                  <h5>{{ item.category }}</h5>
                </a>
                <h5>
                  <strong>
                    <a href="{{ item.get_absolute_url }}" class="dark-grey-text"> {{ item.title }}
                      {% if item.label %}
                          <span class="badge badge-pill danger-color">{{ item.get_label_display }}</span>
                      
                      {% endif %}
                    </a>
                  </strong>
                </h5>

                <h4 class="font-weight-bold blue-text">
                  <strong>${{ item.get_item_price }}</strong>
                </h4>

              </div>
              <!--Card content-->

            </div>
            <!--Card-->

          </div>
          <!--Grid column-->
          {% endfor %}



        </div>
        <!--Grid row-->

      </section>
      <!--Section: Products v.3-->

      {% include '_pagination.html' %}

    </div>
  </main>
  <!--Main layout-->

{% endblock content %}

templates/order_summary.html
{% extends "_base.html" %}

{% block content %}
  <main class="mt-3">
    <div class="container">

    <div class="table-responsive text-nowrap">
    <h2>Order Summary</h2>
    <table class="table">
        <thead>
        <tr>
            <th scope="col">#</th>
            <th scope="col">Item title</th>
            <th scope="col">Price</th>
            <th scope="col">Quantity</th>
            <th scope="col">Total Item Price</th>
        </tr>
        </thead>
        <tbody>
        {% for order_item in orderitem_list %}
        <tr>
            <th scope="row">{{ forloop.counter }}</th>
            <td>{{ order_item.item.title }}</td>
            <td>
                {% if order_item.item.discount_price %}
                    <del class="mr-2">{{ order_item.item.price }}</del>
                {% endif %}
                {{ order_item.item.get_item_price }}
            </td>
            <td>
                <a href="{% url 'remove_single_item_from_cart' order_item.item.slug %}"><i class="fas fa-minus mr-2"></i></a>
                {{ order_item.quantity }}
                <a href="{% url 'add_to_cart' order_item.item.slug %}"><i class="fas fa-plus ml-2"></i></a>
            </td>
            <td>
            {% if order_item.item.discount_price %}
                ${{ order_item.get_total_item_price }}
                <span class="badge badge-primary">Saving ${{ order_item.get_total_discount_price }}</span>
            {% else %}
                ${{ order_item.get_total_item_price }}
            {% endif %}
            <a style='color: red;' href="{% url 'remove_from_cart' order_item.item.slug %}">
                <i class="fas fa-trash float-right"></i>
            </a>
            </td>
        </tr>
        {% empty %}
        <tr>
            <td colspan='5'>Your cart is empty</td>
        </tr>
        <tr>
            <td colspan="5">
            <a class='btn btn-primary float-right' href='/'>Continue shopping</a>
            </td>
        </tr>
        {% endfor %}
        {% if order.coupon %}
        <tr>    
            <td colspan="4"><b>Coupon</b></td>
            <td><b>-${{ order.coupon.amount }}</b></td>
        </tr>
        {% endif %}
        {% if order.get_total %}
        <tr>
            <td colspan="4"><b>Order Total</b></td>
            <td><b>${{ order.get_total }}</b></td>
        </tr>
        <tr>
            <td colspan="5">
            <a class='btn btn-warning float-right ml-2' href='{% url "checkout" %}'>Proceed to checkout</a>
            <a class='btn btn-primary float-right' href='{% url "home_page" %}'>Continue shopping</a>
            </td>
        </tr>
        {% endif %}
        </tbody>
    </table>

    </div>

    </div>

  </main>

{% endblock content %}

templates/product-page.html
{% extends "_base.html" %}
{% load static %}

{% block content %}
    
  <main class="pt-4">
    <div class="container dark-grey-text mt-5">

      <!--Grid row-->
      <div class="row wow fadeIn">

        <!--Grid column-->
        <div class="col-md-6 mb-4">

          <img src="{{ item.image.url }}" class="img-fluid" alt="" style="max-height: 500px; margin: 0 auto">

        </div>
        <!--Grid column-->

        <!--Grid column-->
        <div class="col-md-6 mb-4">

          <!--Content-->
          <div class="p-4">

            <div class="mb-3">
              <a href="{% url 'by_category' slug=item.category.slug %}">
                <span class="badge purple mr-1">{{ item.category.name }}</span>
              </a>
              {% if item.label %}
                  <a href="">
                    <span class="badge blue mr-1">{{ item.get_label_display }}</span>
                  </a>
              {% endif %}
            </div>

            <p class="lead">
              {% if item.discount_price %}
                  <span class="mr-1">
                    <del>${{ item.price }}</del>
                  </span>
              {% endif %}
              <span>${{ item.get_item_price }}</span>
            </p>

            <p class="lead font-weight-bold">Description</p>

            <p>{{ item.description }}</p>

            <div class="d-flex justify-content-left">
              <!-- Default input -->
              {% if not already_added %}
                  <a href="{% url 'add_to_cart' slug=item.slug %}" class="btn btn-primary btn-md my-0 p" type="submit">Add to cart
                    <i class="fas fa-shopping-cart ml-1"></i>
                  </a>

              {% else %}
                  <a href="{% url 'remove_from_cart' slug=item.slug %}" class="btn btn-warning btn-md my-0 p" type="submit">Remove from cart
                    <i class="fas fa-shopping-cart ml-1"></i>
                  </a>
              {% endif %}

            </form>

          </div>
          <!--Content-->

        </div>
        <!--Grid column-->

      </div>
      <!--Grid row-->

      <hr>

      <!--Grid row-->
      <div class="row d-flex justify-content-center wow fadeIn">

        <!--Grid column-->
        <div class="col-md-6 text-center">

          <h4 class="my-4 h4">Additional information</h4>

          <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Natus suscipit modi sapiente illo soluta odit
            voluptates,
            quibusdam officia. Neque quibusdam quas a quis porro? Molestias illo neque eum in laborum.</p>

        </div>
        <!--Grid column-->

      </div>
      <!--Grid row-->

      <!--Grid row-->
      <div class="row wow fadeIn">

        {% for item in related_items %}
          
        <!--Grid column-->
        <a href="{{ item.get_absolute_url }}" class="col-lg-4 col-md-12 mb-4">
          <div style="width: 100%; height: 250px;">
            
            <img src="{{ item.image.url }}" class="img-fluid" alt="" style="width: 100%; height: 100%; object-fit: cover">

          </div>

        </a>
        <!--Grid column-->

        {% endfor %}
      </div>
      <!--Grid row-->

    </div>
  </main>

{% endblock content %}

templates/results.html
{% extends "_base.html" %}

{% block content %}
    
	<div class="container mt-3">
		<!--Section: Products v.3-->
<section class="text-center mb-4">

<!--Grid row-->
<div class="row wow fadeIn">

  {% for item in item_list %}
    
  <!--Grid column-->
  <div class="col-lg-3 col-md-6 mb-4">

    <!--Card-->
    <div class="card">

      <!--Card image-->
      <div class="view overlay" style="height: 200px;">
        <img src="{{ item.image.url }}" class="card-img-top" style="width: 100%; height: 100%; object-fit: cover;"
          alt="">
        <a href="{{ item.get_absolute_url }}">
          <div class="mask rgba-white-slight"></div>
        </a>
      </div>
      <!--Card image-->

      <!--Card content-->
      <div class="card-body text-center">
        <!--Category & Title-->
        <a href="" class="grey-text">
          <h5>{{ item.category }}</h5>
        </a>
        <h5>
          <strong>
            <a href="" class="dark-grey-text"> {{ item.title }}
              {% if item.label %}
                  <span class="badge badge-pill danger-color">{{ item.get_label_display }}</span>
              
              {% endif %}
            </a>
          </strong>
        </h5>

        <h4 class="font-weight-bold blue-text">
          <strong>${{ item.get_item_price }}</strong>
        </h4>

      </div>
      <!--Card content-->

    </div>
    <!--Card-->

  </div>
  <!--Grid column-->
  {% endfor %}



</div>
<!--Grid row-->

{% include '_pagination.html' %}

</section>
	</div>


{% endblock content %}